/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorldsRouteImport } from './routes/worlds'
import { Route as VersionsRouteImport } from './routes/versions'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ServersRouteImport } from './routes/servers'
import { Route as PublicServersRouteImport } from './routes/public-servers'
import { Route as NewsRouteImport } from './routes/news'
import { Route as ModsRouteImport } from './routes/mods'
import { Route as ModpacksRouteImport } from './routes/modpacks'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServerHostingIndexRouteImport } from './routes/server-hosting/index'
import { Route as InstallationsIndexRouteImport } from './routes/installations/index'
import { Route as ModConfigsIdRouteImport } from './routes/mod-configs/$id'
import { Route as ServerHostingIdIndexRouteImport } from './routes/server-hosting/$id/index'
import { Route as ServerHostingIdModsRouteImport } from './routes/server-hosting/$id/mods'
import { Route as InstallationsIdModsRouteImport } from './routes/installations/$id/mods'

const WorldsRoute = WorldsRouteImport.update({
  id: '/worlds',
  path: '/worlds',
  getParentRoute: () => rootRouteImport,
} as any)
const VersionsRoute = VersionsRouteImport.update({
  id: '/versions',
  path: '/versions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ServersRoute = ServersRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicServersRoute = PublicServersRouteImport.update({
  id: '/public-servers',
  path: '/public-servers',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ModsRoute = ModsRouteImport.update({
  id: '/mods',
  path: '/mods',
  getParentRoute: () => rootRouteImport,
} as any)
const ModpacksRoute = ModpacksRouteImport.update({
  id: '/modpacks',
  path: '/modpacks',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerHostingIndexRoute = ServerHostingIndexRouteImport.update({
  id: '/server-hosting/',
  path: '/server-hosting/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallationsIndexRoute = InstallationsIndexRouteImport.update({
  id: '/installations/',
  path: '/installations/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModConfigsIdRoute = ModConfigsIdRouteImport.update({
  id: '/mod-configs/$id',
  path: '/mod-configs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerHostingIdIndexRoute = ServerHostingIdIndexRouteImport.update({
  id: '/server-hosting/$id/',
  path: '/server-hosting/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerHostingIdModsRoute = ServerHostingIdModsRouteImport.update({
  id: '/server-hosting/$id/mods',
  path: '/server-hosting/$id/mods',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallationsIdModsRoute = InstallationsIdModsRouteImport.update({
  id: '/installations/$id/mods',
  path: '/installations/$id/mods',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/modpacks': typeof ModpacksRoute
  '/mods': typeof ModsRoute
  '/news': typeof NewsRoute
  '/public-servers': typeof PublicServersRoute
  '/servers': typeof ServersRoute
  '/settings': typeof SettingsRoute
  '/versions': typeof VersionsRoute
  '/worlds': typeof WorldsRoute
  '/mod-configs/$id': typeof ModConfigsIdRoute
  '/installations/': typeof InstallationsIndexRoute
  '/server-hosting/': typeof ServerHostingIndexRoute
  '/installations/$id/mods': typeof InstallationsIdModsRoute
  '/server-hosting/$id/mods': typeof ServerHostingIdModsRoute
  '/server-hosting/$id/': typeof ServerHostingIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/modpacks': typeof ModpacksRoute
  '/mods': typeof ModsRoute
  '/news': typeof NewsRoute
  '/public-servers': typeof PublicServersRoute
  '/servers': typeof ServersRoute
  '/settings': typeof SettingsRoute
  '/versions': typeof VersionsRoute
  '/worlds': typeof WorldsRoute
  '/mod-configs/$id': typeof ModConfigsIdRoute
  '/installations': typeof InstallationsIndexRoute
  '/server-hosting': typeof ServerHostingIndexRoute
  '/installations/$id/mods': typeof InstallationsIdModsRoute
  '/server-hosting/$id/mods': typeof ServerHostingIdModsRoute
  '/server-hosting/$id': typeof ServerHostingIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/modpacks': typeof ModpacksRoute
  '/mods': typeof ModsRoute
  '/news': typeof NewsRoute
  '/public-servers': typeof PublicServersRoute
  '/servers': typeof ServersRoute
  '/settings': typeof SettingsRoute
  '/versions': typeof VersionsRoute
  '/worlds': typeof WorldsRoute
  '/mod-configs/$id': typeof ModConfigsIdRoute
  '/installations/': typeof InstallationsIndexRoute
  '/server-hosting/': typeof ServerHostingIndexRoute
  '/installations/$id/mods': typeof InstallationsIdModsRoute
  '/server-hosting/$id/mods': typeof ServerHostingIdModsRoute
  '/server-hosting/$id/': typeof ServerHostingIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/modpacks'
    | '/mods'
    | '/news'
    | '/public-servers'
    | '/servers'
    | '/settings'
    | '/versions'
    | '/worlds'
    | '/mod-configs/$id'
    | '/installations/'
    | '/server-hosting/'
    | '/installations/$id/mods'
    | '/server-hosting/$id/mods'
    | '/server-hosting/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/modpacks'
    | '/mods'
    | '/news'
    | '/public-servers'
    | '/servers'
    | '/settings'
    | '/versions'
    | '/worlds'
    | '/mod-configs/$id'
    | '/installations'
    | '/server-hosting'
    | '/installations/$id/mods'
    | '/server-hosting/$id/mods'
    | '/server-hosting/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/modpacks'
    | '/mods'
    | '/news'
    | '/public-servers'
    | '/servers'
    | '/settings'
    | '/versions'
    | '/worlds'
    | '/mod-configs/$id'
    | '/installations/'
    | '/server-hosting/'
    | '/installations/$id/mods'
    | '/server-hosting/$id/mods'
    | '/server-hosting/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ModpacksRoute: typeof ModpacksRoute
  ModsRoute: typeof ModsRoute
  NewsRoute: typeof NewsRoute
  PublicServersRoute: typeof PublicServersRoute
  ServersRoute: typeof ServersRoute
  SettingsRoute: typeof SettingsRoute
  VersionsRoute: typeof VersionsRoute
  WorldsRoute: typeof WorldsRoute
  ModConfigsIdRoute: typeof ModConfigsIdRoute
  InstallationsIndexRoute: typeof InstallationsIndexRoute
  ServerHostingIndexRoute: typeof ServerHostingIndexRoute
  InstallationsIdModsRoute: typeof InstallationsIdModsRoute
  ServerHostingIdModsRoute: typeof ServerHostingIdModsRoute
  ServerHostingIdIndexRoute: typeof ServerHostingIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/worlds': {
      id: '/worlds'
      path: '/worlds'
      fullPath: '/worlds'
      preLoaderRoute: typeof WorldsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/versions': {
      id: '/versions'
      path: '/versions'
      fullPath: '/versions'
      preLoaderRoute: typeof VersionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servers': {
      id: '/servers'
      path: '/servers'
      fullPath: '/servers'
      preLoaderRoute: typeof ServersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public-servers': {
      id: '/public-servers'
      path: '/public-servers'
      fullPath: '/public-servers'
      preLoaderRoute: typeof PublicServersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mods': {
      id: '/mods'
      path: '/mods'
      fullPath: '/mods'
      preLoaderRoute: typeof ModsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modpacks': {
      id: '/modpacks'
      path: '/modpacks'
      fullPath: '/modpacks'
      preLoaderRoute: typeof ModpacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/server-hosting/': {
      id: '/server-hosting/'
      path: '/server-hosting'
      fullPath: '/server-hosting/'
      preLoaderRoute: typeof ServerHostingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/installations/': {
      id: '/installations/'
      path: '/installations'
      fullPath: '/installations/'
      preLoaderRoute: typeof InstallationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mod-configs/$id': {
      id: '/mod-configs/$id'
      path: '/mod-configs/$id'
      fullPath: '/mod-configs/$id'
      preLoaderRoute: typeof ModConfigsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/server-hosting/$id/': {
      id: '/server-hosting/$id/'
      path: '/server-hosting/$id'
      fullPath: '/server-hosting/$id/'
      preLoaderRoute: typeof ServerHostingIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/server-hosting/$id/mods': {
      id: '/server-hosting/$id/mods'
      path: '/server-hosting/$id/mods'
      fullPath: '/server-hosting/$id/mods'
      preLoaderRoute: typeof ServerHostingIdModsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/installations/$id/mods': {
      id: '/installations/$id/mods'
      path: '/installations/$id/mods'
      fullPath: '/installations/$id/mods'
      preLoaderRoute: typeof InstallationsIdModsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ModpacksRoute: ModpacksRoute,
  ModsRoute: ModsRoute,
  NewsRoute: NewsRoute,
  PublicServersRoute: PublicServersRoute,
  ServersRoute: ServersRoute,
  SettingsRoute: SettingsRoute,
  VersionsRoute: VersionsRoute,
  WorldsRoute: WorldsRoute,
  ModConfigsIdRoute: ModConfigsIdRoute,
  InstallationsIndexRoute: InstallationsIndexRoute,
  ServerHostingIndexRoute: ServerHostingIndexRoute,
  InstallationsIdModsRoute: InstallationsIdModsRoute,
  ServerHostingIdModsRoute: ServerHostingIdModsRoute,
  ServerHostingIdIndexRoute: ServerHostingIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
