name: Code quality

on:
  merge_group:
  push:
    branches:
      - release
    paths:
      - "**.ts"
      - "**.tsx"
      - "**.js"
      - "**.jsx"
      - "**.json"
      - "**.css"
      - "**.scss"
  pull_request:
    branches:
      - release
    paths:
      - "**.ts"
      - "**.tsx"
      - "**.js"
      - "**.jsx"
      - "**.json"
      - "**.css"
      - "**.scss"
    types:
      - opened
      - synchronize

jobs:
  lint:
    runs-on: ubuntu-slim
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false

      - name: setup bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6
        with:
          no-cache: true

      - name: install dependencies
        run: bun install

      - name: Run Lint
        run: bun run lint

      - name: Run Format Check
        run: bun run fmt:check
